[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python start.py"
# Disable health checks temporarily to bypass deployment issues
# healthcheckPath = "/health"
# healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
ENVIRONMENT = "production"
PYTHONPATH = "/app"
LOG_LEVEL = "INFO"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"

# CORS settings for production
ALLOWED_ORIGINS = "https://your-frontend-domain.com,https://vriddhi-app.railway.app"

# Application settings
API_V1_STR = "/api/v1"
DEFAULT_EXPECTED_CAGR = "0.15"
MIN_MONTHLY_INVESTMENT = "50000"

[build.env]
PIP_NO_CACHE_DIR = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"